AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for VPC resources'

Parameters: {}

Resources:
  MyVpc:
    Type: 'CRC-VPC
    Properties: 
      CidrBlock: '172.31.0.0/16'
      DhaptionsId: 'dopt-cdb288b7'
      IsDefault: true
      Tags: []
      State: 'available'

  MySubnet1:
    Type: 'CRC-Subnet'
    Properties:
      VppId: 'ref: MyVpc'
      CidrBlock: '172.31.32.0/20'
      AvailabilityZone: 'us-east-1a'
      MapPublicIpOnLaunch: true
      State: 'available'

  MySubnet2:
    Type: 'CRC-Subnet'
    Properties:
      VppId: 'ref: MyVpc'
      CidrBlock: '172.31.0.0/20'
      AvailabilityZone: 'us-east-1b'
      MapPublicIpOnLaunch: true
      State: 'available'

  MySubnet3: 
    Type: 'CRC-Subnet'
    Properties:
      VppId: 'ref: MyVpc'
      CidrBlock: '172.31.80.0/20'
      AvailabilityZone: 'us-east-1c'
      MapPublicIpOnLaunch: true
      State: 'available'

  MySubnet4:
    Type: 'CRC-Subnet'
    Properties:
      VppId: 'ref: MyVpc'
      CidrBlock: '172.31.16.0/20'
      AvailabilityZone: 'us-east-1d'
      MapPublicIpOnLaunch: true
      State: 'available'

  MySubnet5:
    Type: 'CRC-Subnet'
    Properties:
      VppId: 'ref: MyVpc'
      CidrBlock: '172.31.64.0/20'
      AvailabilityZone: 'us-east-1f'
      MapPublicIpOnLaunch: true
      State: 'available'

  MySubnet6:
    Type: 'CRC-Subnet'
    Properties:
      VppId: 'ref: MyVpc'
      CidrBlock: '172.31.48.0/20'
      AvailabilityZone: 'us-east-1e'
      MapPublicIpOnLaunch: true
      State: 'available'

  MyInternetGateway: 
    Type: 'CRC-InternetGateway'
    Properties:
      Tags: []
      Attachments:
        - State: 'available'
          VpcId: ref: MyVpc'
       InternetGatewayId: "igw-b8529ec2"

  MyRouteTable:
    Type: 'CRC-RouteTable'
    Properties:
      VpcId: ref: MyVpc'
      Routes:
        - DestinationCidrBloc: '172.31.0.0/16'
          GatewayId: 'local'
        - DestinationCidrBlock: '0.0.0.0/0'
          GatewayId: 'igw-b8529ec2'

  MySecurityGroup:
    Type: 'CRC-SecurityGroup'
    Properties:
      VpcId: ref: MyVpc'
      GroupName: 'default'
      GroupDescription: 'default VPC security group'
      IpParameters:
        - IpProtocol: '-1'
          UserIdGroupPairs:
          - UserId: '661572124387'
            GroupId: 'sg-14c90b0c'
        IpRanges: 
          - CidrIp: '0.0.0.0/0'
        Ip6 Ranges: []
        PrefixListIds: []

Outputs:
  VpcId:
    Value: ref: MyVpc
    Lexport: VpcId